live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Light Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "Enter"
mods = "Command"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.95
startup_mode = "Fullscreen"

[window.dimensions]
columns = 130
lines = 25
